<?php
return [
    // ── Brand / nav ────────────────────────────────────────────
    'site_name'        => "Nour's Touch",
    'home'             => 'Home',
    'about'            => 'About',
    'about_title'      => 'About Us',
    'services'         => 'Services',
    'therapists'       => 'Therapists',
    'packages'         => 'Packages',
    'gallery'          => 'Gallery',
    'blog'             => 'Journal',
    'contact'          => 'Contact',
    'book_now'         => 'Book Now',
    'whatsapp_us'      => 'WhatsApp',
    'whatsapp_consult' => 'Quick Consult',

    // ── Hero ───────────────────────────────────────────────────
    'hero_kicker'        => 'Multi-specialty Clinic · Amman',
    'moh_certified'      => 'Licensed by the Jordanian Ministry of Health',
    'moh_certified_sub'  => 'Certified medical team · Highest safety standards',
    'years_experience'   => 'Years of practice',
    'happy_clients'      => 'Patients seen',
    'services_label'     => 'Specialties',

    // ── Trust strip ────────────────────────────────────────────
    'online_booking'     => 'Online booking',
    'online_booking_sub' => 'Confirmed within an hour',
    'open_daily'         => 'Open daily',
    'certified_team'     => 'Certified team',
    'certified_team_sub' => 'Licensed expertise',
    'free_assess'        => 'Free assessment',
    'free_assess_sub'    => 'With your first visit',

    // ── Conditions ────────────────────────────────────────────
    'what_we_treat' => 'Conditions we treat',
    'conditions_h'  => "If you're dealing with <em>any of these</em>, we're here for you.",
    'conditions_sub'=> 'We treat a wide range of chronic conditions and injuries, with treatment plans tailored to your diagnosis.',
    'see_all'       => 'All specialties',

    // ── Home: services ────────────────────────────────────────
    'our_services'        => 'Our services',
    'home_services_h'     => 'Thoughtful therapies, <em>in skilled hands</em>.',
    'home_services_sub'   => 'Every session begins with understanding your case, and ends with a step forward in your recovery.',
    'min'                 => 'min',

    // ── How it works ──────────────────────────────────────────
    'how_it_works'   => 'How it works',
    'home_how_h'     => 'From <em>booking</em> to <em>recovery</em> — four simple steps.',
    'home_how_sub'   => "We follow a clear approach that starts by understanding you and turns every session into a real step forward.",
    'step_1'         => 'Book your visit',
    'step_1_p'       => 'Choose the specialty and time that suits you, online or via WhatsApp.',
    'step_2'         => 'Free assessment',
    'step_2_p'       => 'A diagnostic session with your therapist to set a tailored treatment plan.',
    'step_3'         => 'Treatment sessions',
    'step_3_p'       => 'We begin the program with the latest techniques in a calm, private space.',
    'step_4'         => 'Follow-up',
    'step_4_p'       => 'Regular reviews and plan adjustments until you fully recover.',

    // ── Why us ────────────────────────────────────────────────
    'why_us'    => 'Why Nour\'s Touch',
    'why_h'     => 'More than a clinic — <em>a complete care experience</em>.',
    'why_sub'   => 'A unique experience that combines medical precision and specialty with the warmth of genuine human care.',
    'why_1_t'   => 'Multidisciplinary team',
    'why_1_p'   => 'Physiotherapists, massage specialists, and medical consultants — working together for you.',
    'why_2_t'   => 'Tailored treatment plan',
    'why_2_p'   => 'Every plan is built around your specific diagnosis — never a template.',
    'why_3_t'   => 'Safe and private environment',
    'why_3_p'   => 'Private rooms, strict sterilisation, and full respect for your comfort and privacy.',

    // ── Team ──────────────────────────────────────────────────
    'our_team'        => 'Our team',
    'home_team_h'     => 'Meet our <em>expert hands</em>.',
    'home_team_sub'   => 'Therapists from among the top talents in Jordan.',
    'meet_the_team'   => 'View the whole team',
    'certified'       => 'Certified',

    // ── Packages (Home) ───────────────────────────────────────
    'home_pkg_h_2'         => 'Packages that combine <em>savings</em> and <em>continuity</em>.',
    'home_pkg_sub'         => 'For continuous treatment and routine care — at better rates than per-session pricing.',
    'best_value'           => 'Best value',
    'signature_package'    => 'Signature package',
    'per_session'          => 'Per session',
    'sessions_count'       => 'Sessions included',
    'flexible_book'        => 'Bookable any time',
    'valid_days_label'     => 'Days valid',
    'use_within'           => 'Use at your pace',
    'priority_booking'     => 'Priority booking',
    'free_consultation'    => 'Free consultation',
    'progress_report'      => 'Progress report',
    'choose_this_package'  => 'Choose this package',
    'more_options'         => 'More options',
    'sessions'             => 'sessions',
    'day'                  => 'days',
    'sess'                 => 'session',
    'pkg_guarantee'        => 'Refund of any unused balance within 14 days for any package not yet started.',

    // ── Journal ───────────────────────────────────────────────
    'journal'           => 'Journal',
    'home_journal_h'    => 'Tips and reads from <em>our team</em>.',
    'home_journal_sub'  => 'Articles on health, therapy, and everyday wellness.',

    // ── Visit / CTA ───────────────────────────────────────────
    'visit'              => 'Visit us',
    'visit_h'            => 'Everything you need <em>under one roof</em>.',
    'visit_p'            => "Book your visit or come see us at the clinic. Our reception team is here to help.",
    'start_today'        => 'Start today',
    'book_session_now'   => 'Book your session<br>in a minute.',

    // ── About page ────────────────────────────────────────────
    'our_story_kicker'   => 'Our story · Our vision',
    'about_h'            => 'A touch <em>that makes a difference</em>,<br>care you deserve.',
    'about_lead'         => 'At Nour\'s Touch, we believe healing isn\'t purely medical — it\'s a fully human experience. Since opening our doors, we\'ve blended science with care to offer every patient the treatment they deserve.',

    'years_practice'     => 'Years of practice',
    'patients_treated'   => 'Patients seen',
    'sessions_completed' => 'Sessions completed',
    'specialties'        => 'Therapy specialties',

    'our_philosophy'     => 'Our philosophy',
    'phil_h'             => 'Real healing starts <em>by listening</em>.',
    'phil_p1'            => 'Every patient has a story, and every body has its own rhythm. We spend time with each person to truly understand the case before recommending any protocol.',
    'phil_p2'            => 'We combine the latest in rehabilitative medicine with traditional therapeutic approaches — in a calm, private space that feels like home.',
    'founders'           => 'Founding team',

    'our_values'         => 'Our values',
    'values_h'           => 'What guides every <em>session</em> we offer.',
    'values_sub'         => 'Four values that capture who we are — visible in every detail, from the moment you walk in.',
    'value_1_h'          => 'Certified expertise',
    'value_1_p'          => 'Our team of physiotherapists, massage specialists, and medical consultants are all officially licensed with years of experience.',
    'value_2_h'          => 'Genuine care',
    'value_2_p'          => "Treatment isn't complete with tools alone — we listen, answer your questions, and accompany you every step of the way.",
    'value_3_h'          => 'Safety and privacy',
    'value_3_p'          => "Strict sterilisation protocols, private rooms for every client, and complete confidentiality of your medical information.",
    'value_4_h'          => 'Continuous growth',
    'value_4_p'          => 'We stay current with the latest research and train continuously — today\'s "newest" can become tomorrow\'s norm.',

    'about_team_h'       => 'Faces you\'ll meet at <em>your visit</em>.',
    'about_team_sub'     => 'Specialists working in harmony to deliver a complete treatment experience.',

    'faqs'               => 'Frequently asked',
    'faq_h'              => 'Quick answers to <em>the most common</em> questions.',
    'faq_sub'            => "Didn't find what you were looking for? Reach out directly — we're here to help.",

    'about_visit_h'      => 'We look forward <em>to meeting you</em>.',
    'about_visit_p'      => 'Book your appointment or visit us at the clinic — we\'re waiting for you.',

    // ── Footer ────────────────────────────────────────────────
    'footer_about'         => 'Physiotherapy · Massage · Cupping · Exfoliation · Consults. All with expert hands and a warm touch.',
    'explore'              => 'Explore',
    'all_rights_reserved'  => 'All rights reserved.',
    'crafted_in'           => 'Crafted with care in Amman.',

    // ── Services page ─────────────────────────────────────────
    'all'                       => 'All',
    'services_h'                => 'Therapies in <em>expert hands</em>,<br>worth experiencing.',
    'services_lead'             => "A complete range of therapeutic and aesthetic sessions. Every service is tailored to your case, in a calm space with a professional team.",
    'total_services'            => 'services available',
    'services_in_category'      => 'services in this specialty',
    'services_certified_line'   => 'All sessions are delivered by certified therapists',
    'no_services_yet'           => 'No services available right now.',
    'check_back'                => 'Browse all services or reach out for questions.',
    'not_sure'                  => "Not sure what suits you?",
    'services_cta_h'            => 'Let us help you <em>choose</em>.',
    'services_cta_p'            => "Book a free assessment with our specialists — together we'll find the right session or package for your case.",
    'free_assessment'           => 'Free assessment',
    'book_assessment_h'         => 'Book your free<br>assessment.',

    // ── Therapists page ──────────────────────────────────────
    'team_h'              => 'Skilled hands, <em>honest hearts</em>.',
    'team_lead'           => 'Meet our therapists and consultants — each carrying long experience and a genuine passion for your healing journey.',
    'team_members_label'  => 'specialists at your service',
    'team_certified_line' => "All officially licensed with long-standing experience",
    'book_with'           => 'Book with',
    'no_team_yet'         => 'No team members on display right now.',
    'team_check_back'     => 'Reach out to learn more about our clinic team.',
    'one_team'            => 'One team, one result',
    'team_cta_h'          => 'Looking for the <em>right therapist</em>?',
    'team_cta_p'          => "Book a free assessment session, and we'll match you with the therapist best suited to your case.",

    // ── Packages page ───────────────────────────────────────
    'packages_page_h'    => 'Save more with <em>session packages</em>.',
    'packages_page_lead' => 'Thoughtfully designed packages for continuity. Choose what fits your plan, at rates better than per-session.',
    'per_session_label'  => 'per session',
    'included_services'  => 'Included services',
    'more_packages_h'    => 'More packages <em>to fit your needs</em>.',
    'more_packages_sub'  => 'A selection of smaller packages in different sizes to match your session count.',
    'more'               => 'more',
    'refund_g'           => 'Safe refund',
    'refund_g_p'         => 'Refund of any unused balance within 14 days for untouched packages.',
    'priority_g'         => 'Priority booking',
    'priority_g_p'       => 'Reserve preferred time slots before others.',
    'consult_g'          => 'Free consultation',
    'consult_g_p'        => 'An initial assessment with our specialists before you start.',
    'flexible_g'         => 'Full flexibility',
    'flexible_g_p'       => 'Reschedule any session with 24 hours notice.',
    'no_packages_yet'    => 'No active packages right now.',
    'check_services'     => 'Browse our individual services or reach out for questions.',
    'not_sure_pkg'       => 'Unsure which package suits you?',
    'packages_cta_h'     => 'Ask us — <em>we choose with you</em>.',
    'packages_cta_p'     => "Reach out and we'll help you pick the package best aligned with your case and plan.",

    // ── Gallery page ────────────────────────────────────────
    'gallery_h'           => 'A visual tour of <em>our clinic</em>.',
    'gallery_lead'        => 'Snapshots from our treatment rooms, facilities, and everyday atmosphere — all designed for your comfort.',
    'total_photos'        => 'photos in the gallery',
    'photos'              => 'photos',
    'gallery_tip'         => 'Click any image to view it full size',
    'no_photos_yet'       => 'No photos in this category yet.',
    'photos_check_back'   => 'Browse all photos or visit our clinic.',
    'gallery_cta_h'       => 'Photos tell a story — <em>the experience completes with you</em>.',
    'gallery_cta_p'       => "Book your session and experience the atmosphere you see in these photos.",

    // ── Blog page ───────────────────────────────────────────
    'blog_h'              => 'Reads on <em>health and wellness</em>.',
    'blog_lead'           => 'Tips and articles from our team — about health, therapy, and daily care.',
    'search'              => 'Search',
    'search_articles'     => 'Search articles…',
    'featured'            => 'Featured',
    'read_article'        => 'Read article',
    'prev'                => 'Previous',
    'next'                => 'Next',
    'no_posts_yet'        => 'No published articles yet.',
    'no_posts_found'      => 'No results for your search.',
    'check_back_later'    => 'Check back soon for new content.',

    // ── Blog single (article) ──────────────────────────────
    'author'              => 'Author',
    'min_read'            => 'min read',
    'share'               => 'Share',
    'written_by'          => 'Written by',
    'published_on'        => 'Published on',
    'reading_time'        => 'Reading time',
    'share_this'          => 'Share this article',
    'back_to_blog'        => 'All articles',
    'related'             => 'Related',
    'related_articles'    => 'Articles you might <em>enjoy</em>.',
    'related_sub'         => 'Continue reading with posts in the same category.',
    'read'                => 'Read',
    'liked_article'       => 'Liked this article?',
    'blog_cta_h'          => 'Advice is <em>complete</em> with a session.',
    'blog_cta_p'          => "Read first, then experience it — book a free assessment with our specialists.",

    // ── Contact page ──────────────────────────────────────────
    'get_in_touch'        => 'Get in touch',
    'contact_h'           => "We'd love to hear from <em>you</em>.",
    'contact_lead'        => 'Ask, consult, or book — our team replies within working hours.',
    'call_us'             => 'Call us',
    'email_us'            => 'Email us',
    'quick_reply'         => 'Quick reply',
    'working_hours'       => 'Working hours',
    'send_message'        => 'Send a message',
    'contact_form_h'      => "Write to us — <em>we'll reply</em>.",
    'contact_form_p'      => 'Whether a consultation, a question about a service, or a note — every message reaches us, and we aim to reply within 24 hours.',
    'full_name'           => 'Full name',
    'phone'               => 'Phone',
    'email'               => 'Email',
    'subject'             => 'Subject',
    'message'             => 'Message',
    'message_ph'          => 'Write your message here…',
    'contact_privacy'     => 'Your details are private — we never share with third parties.',
    'send'                => 'Send',
    'thanks'              => 'Thank you',
    'contact_ok'          => "Your message reached us — we'll get back to you soon.",
    'contact_err'         => 'Something went wrong, please try again later.',
    'contact_required'    => 'Name and message are required.',
    'email_invalid'       => 'Invalid email address.',
    'message_too_short'   => 'Your message is too short.',
    'spam_detected'       => 'Spam detected.',
    'visit_us'            => 'Visit us',
    'contact_visit_h'     => "We're right here.",
    'address'             => 'Address',
    'follow_us'           => 'Follow us',
    'book_a_session'      => 'Book a session',
    'book_a_session_sub'  => 'Booking takes only one minute.',

    // ── Booking page ──────────────────────────────────────────
    'booking'             => 'Book an appointment',
    'booking_h'           => 'Book your session <em>in a minute</em>.',
    'booking_lead'        => "Choose the service, therapist, and time — we'll reach out to confirm.",
    'booking_form'        => 'Booking details',
    'booking_form_h'      => 'Tell us a bit <em>about you</em>.',
    'booking_form_p'      => 'A few details are all we need to confirm your appointment.',
    'your_details'        => 'Your details',
    'email_optional'      => 'Email (optional)',
    'choose_service'      => 'Choose a service',
    'service'             => 'Service',
    'select_service'      => 'Select a service',
    'therapist'           => 'Therapist',
    'therapist_optional'  => 'Therapist (optional)',
    'any_therapist'       => 'Any available therapist',
    'pick_time'           => 'Pick a time',
    'date_time'           => 'Date & time',
    'availability'        => 'Availability',
    'avail_idle'          => 'Choose service and time to check availability…',
    'avail_checking'      => 'Checking…',
    'avail_ok'            => 'Time is available',
    'avail_bad'           => 'Time is not available',
    'avail_pick_time'     => 'Pick a time first',
    'notes_optional'      => 'Notes (optional)',
    'notes_ph'            => 'Anything you would like to share with us…',
    'send_request'        => 'Send booking request',
    'booking_confirm_note'=> "We'll reach you during working hours to confirm.",
    'booking_required'    => 'Name and phone are required.',
    'booking_time_invalid'=> 'Please choose a valid time.',
    'booking_time_past'   => 'You cannot pick a time in the past.',
    'booking_err'         => 'Something went wrong, please try again later.',
    'booking_received'    => 'Booking request received',
    'booking_received_p'  => "Thank you — our team will contact you shortly to confirm your appointment.",
    'back_to_home'        => 'Back to home',
    'browse_services'     => 'Browse services',
    'your_booking'        => 'Your booking',
    'booking_summary'     => 'Appointment summary',
    'duration'            => 'Duration',
    'appointment'         => 'Appointment',
    'estimated_total'     => 'Estimated total',
    'booking_re1'         => 'No commitment',
    'booking_re1_p'       => 'We confirm the appointment before locking it in.',
    'booking_re2'         => 'Flexible changes',
    'booking_re2_p'       => 'Reschedule up to two hours before.',
    'booking_re3'         => 'Licensed specialists',
    'booking_re3_p'       => 'A trained team with clinical experience.',
    'book_via_wa'         => 'Book via WhatsApp',
    'book_via_wa_p'       => 'We reply in minutes',

    // ── Misc ──────────────────────────────────────────────────
    'currency'         => 'JOD',
    'login'            => 'Login',
    'staff_login'      => 'Staff login',
    'powered_by'       => 'Developed by',
    'register'         => 'Register',
    'logout'           => 'Logout',
    'dashboard'        => 'Dashboard',
];
